name: deploy
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-js-${{ hashFiles('yarn.lock') }}

    - run: yarn install
    - run: yarn build

    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Deploy to GCS
      run: |-
        gsutil -m -h 'Cache-Control:no-cache' rsync -d -r dist 'gs://${{ secrets.BUCKET }}'
    
    - name: Set cache
      run: |-
        gsutil -m setmeta -h 'Cache-Control:public, max-age=31536000' 'gs://${{ secrets.BUCKET }}/*/**'
        gsutil -m setmeta -h 'Cache-Control:public, max-age=31536000' 'gs://${{ secrets.BUCKET }}/*.woff*'
        gsutil -m setmeta -h 'Cache-Control:public, max-age=31536000' 'gs://${{ secrets.BUCKET }}/*.ttf'
